language: node_js
node_js:
- node
- '8'
before_install:
- npm install -g coveralls
script:
- npm run lint
- npm run test
sudo: false
cache:
  directories:
  - node_modules
after_success:
- npm run coverage
- npm run coverage:report