language: node_js
node_js:
- node
- '8'
before_install:
- npm install -g coveralls
script:
- npm run lint
- npm run test
sudo: false
cache:
  directories:
  - node_modules
after_success:
- npm run coverage
- npm run coverage:report
deploy:
  provider: npm
  skip_cleanup: true
  api_key:
    secure: cVy0dPaSquF/UaV57FxAVYnLXuBcmAz8knjd7O2qUIQKp0TRkyiHodkU6iXp2BAc03KVAJBDl5W0kxZj2hSfzQXV7wKznJeavmN2CCuK5ji/7krT8R1u0vrx8ksjugjBW91QqxJABvhoZ5LmiRklq0jjegjeeYvne9Cp8TdswhE4BbfADGErYHLY4WJYyBdscEAg9t3mdTUXkK1nCDyuhHucOq/6gELfsrrKTCi2UvrLnvhs1e+kQkOu05SQnyIVKL0K+0vNpzARZ210NzY0QLWXfLu9+Vut8zyEWGt9qi1dQMKaKHlcrU3Fdg0D70ZD5qlXqLkjXJJ1gWPzODNArPpDnoQK47Pyuz3jsxaWc/XWX2GoLaLlyo/MRWd/54+J0Q+RO3e0N6qjx4A8xTDF6PP/KCLnqrQ+2uQP6IZdlf2mkkxzX5kstJFKz9mjg3i81FuGrGn0CNCFtvK2KuIV3CX9L9BisjlrpRgCahIStoyLv5410VWlrOIEzoL/q360N1t+sRtZlClHCxOqV8FoYiYLHHTFvGuWcn8fEfQWxNUx7wCZaGY4Bag7oWiCTkpOcfoLrOkpBWWsVJGA9gnMMhw0m6w0qz9bAgxCPB+fHlnXmFF27lsQukSahiM41m0/PkaFQYYnG0FCx1tk/WcLPlPGj+zoVP1zSuE7cTz6Nbs=
  email:
    secure: GIsqHBHA0gmkCr68v9Zg1XqR+hDtWGnkaZRHysDkt9zXB6zq3CH78bDDh32ee2qFCoXZstZ9HunDP4h7rQVL22iyQcrfJxECoHNlze6LTi16IRsAQSQ2S2DH+2S4HxTQ/lBn/UVy/+DExK2aYOHwFyj90hyVbdMC9u4tIvjvYLYyL0Fot1xXW9Pn0fPNkEDJwkTdaT3sa3kBF9j50tNKHrYmSNjaWswr9tVtItXVSt4XJM70rzQ7xdQJ4+PWYURDoUxgRyyv/md3dKMCA76HkjwggrWVuuT0S46BNpsPjmTXBONpL7z4M5VFTrAuE4Wg7msPwMcfWykRzrLPURmjCcJ+wU3AtFXPbfk9qtESvPKPp/2Wtuz9hj/rBRUExmjBWPb4ppvfgIUcp2Y9VBf5zZOj501jiexQQJ1DopBnIpC0cpZrny3fOqFWRiojGdnBz0OBeMcBgf1V7IwDlyU1n2fHEu0hXI/ogIcFmSGa0iQ7FAH1SECCcYdwfqPo5ES9GXA1kZOzgrddGjwBdfgJsXdTOFwwltoqhsz3lwRiM9CMKfbLrLSwhSqVeBKfgpmGa4Bgs8rAmcQDoCTzHUzIQDbyhvVu5LUZcY4GWvhxArY7KTaMfwiV1BcZPLVNZ8TWxZuSJJ739NlaNnL3duFrJXwtQS7Q4Rp+j54P9OlyxLI=
  on:
    tags: true
    node: node
    repo: scurker/metalsmith-tweet-embed
